name: Release

on:
    push:
        tags:
            - 'v?[0-9]+.[0-9]+.[0-9]+'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   uses: actions/checkout@v2
                name: Checkout repository
            -   name: Set variables
                id: vars
                run: echo ::set-output name=release_version::${GITHUB_REF#refs/*/}
            -   name: Create release ZIP file
                run: |
                    git archive "${{ steps.vars.outputs.release_version }}" \
                    --format=zip --output="${{ steps.vars.outputs.release_version }}.zip"
            -   uses: ncipollo/release-action@v1
                name: Upload release to GitHub
                with:
                    artifacts: "${{ steps.vars.outputs.release_version }}.zip"
